# Generated by Django 4.0.4 on 2022-04-23 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title : ')),
                ('image', models.ImageField(upload_to='product_img/', verbose_name='Image : ')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title : ')),
            ],
            options={
                'verbose_name': 'MainCategory',
                'verbose_name_plural': 'MainCategorys',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Size : ')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title : ')),
                ('details', models.TextField(verbose_name='Details : ')),
                ('count', models.IntegerField(verbose_name='Count in store')),
                ('img_1', models.ImageField(upload_to='product_img/', verbose_name='Image 1 : ')),
                ('img_2', models.ImageField(upload_to='product_img/', verbose_name='Image 2 : ')),
                ('img_3', models.ImageField(upload_to='product_img/', verbose_name='Image 3 : ')),
                ('is_feature', models.BooleanField(verbose_name='Is Featured : ')),
                ('sale', models.BooleanField(verbose_name='Sale : ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_Price', models.IntegerField(verbose_name='Des Price : ')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('image', models.ImageField(upload_to='product_img/', verbose_name='Image : ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'verbose_name': 'ProductAttr',
                'verbose_name_plural': 'ProductAttrs',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='m_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.maincategory'),
        ),
    ]
