# Generated by Django 4.0.4 on 2022-04-23 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='product_img/', verbose_name='Image   '),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title   '),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title   '),
        ),
        migrations.AlterField(
            model_name='productattr',
            name='image',
            field=models.ImageField(upload_to='product_img/', verbose_name='Image   '),
        ),
        migrations.AlterField(
            model_name='productattr',
            name='old_Price',
            field=models.IntegerField(verbose_name='Des Price   '),
        ),
        migrations.AlterField(
            model_name='productattr',
            name='price',
            field=models.IntegerField(verbose_name='Price '),
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Size '),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title   ')),
                ('details', models.TextField(verbose_name='Details   ')),
                ('count', models.IntegerField(verbose_name='Count in store')),
                ('img_1', models.ImageField(upload_to='product_img/', verbose_name='Image 1   ')),
                ('img_2', models.ImageField(upload_to='product_img/', verbose_name='Image 2   ')),
                ('img_3', models.ImageField(upload_to='product_img/', verbose_name='Image 3   ')),
                ('is_feature', models.BooleanField(verbose_name='Is Featured   ')),
                ('sale', models.BooleanField(verbose_name='Sale   ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.AlterField(
            model_name='productattr',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
