# Generated by Django 4.0.4 on 2022-04-26 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_image_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'Main Category', 'verbose_name_plural': 'MainCategorys'},
        ),
        migrations.AddField(
            model_name='productattr',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.size'),
            preserve_default=False,
        ),
    ]
